repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: name-tests-test
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        entry: poetry run pydocstyle
        args: [ '--add-ignore=D100,D101,D102,D103,D104,D105,D106,D107', '--convention=google' ]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: poetry run coverage run -m pytest
        language: system
        pass_filenames: false
        always_run: true
