repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: name-tests-test
      - id: end-of-file-fixer
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
