# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: make black
        language: system
#        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: name-tests-test     # enforce test file names (e.g. tests/mymodule_test.py)
      - id: trailing-whitespace # trim trailing whitespace
      - id: end-of-file-fixer   # add single empty line at EOF
      - id: no-commit-to-branch # don't commit to `master` or `main` directly
  - repo: https://github.com/python-poetry/poetry
    rev: 1.5.1
    hooks:
      - id: poetry-check
      - id: poetry-lock
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
